version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-dev
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - ./certs:/app/certs
    environment:
      - NODE_ENV=development
      # Add your environment variables here
      - VITE_PFX_PATH=${VITE_PFX_PATH}
      - VITE_PFX_PASSPHRASE=${VITE_PFX_PASSPHRASE}
      - VITE_API_URL=${VITE_API_URL}
    command: npm run dev 