services:
  sql-server-express:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: docker-sql-server-express
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - SQL_StandardUser_PASSWORD=${SQL_StandardUser_PASSWORD}  
      - SQL_MigrationUser_PASSWORD=${SQL_MigrationUser_PASSWORD}
      - MSSQL_PID=Express
      - MSSQL_SETUP_SCRIPT=/scripts/init-database.sql
    ports:
      - "1433:1433"
    volumes:
      - ./sql-data:/var/opt/mssql/data
      - ./init-database.sql:/scripts/init-database.sql
      - ./entrypoint.sh:/entrypoint.sh
    command: /bin/bash /entrypoint.sh

    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${SQL_PASSWORD}" -C -N -Q "SELECT 1" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s

  migration:
    image: mcr.microsoft.com/dotnet/sdk:9.0
    depends_on:
      sql-server-express:
        condition: service_healthy
    volumes:
      - ..:/app    # Mount the entire solution directory
    working_dir: /app/backend/Migrator
    environment:
      - ConnectionStrings__DefaultConnection=${MIGRATOR_CONNECTION_STRING}
    command: >
      sh -c "dotnet restore &&
             dotnet run"

#    command: >
#      sh -c "dotnet tool install --global dotnet-ef &&
#             dotnet restore &&
#             dotnet run &&
#             tail -f /dev/null"

volumes:
  sql-data:
